language: perl
perl:
  - "5.20"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
script:
  PERL5OPT=-MDevel::Cover prove -lv t && cover -report coveralls
notifications:
  email:
    - jacoby.david@gmail.com
    - jacobydavid@live.com
  on_success: always
  on_failure: always 


